import type { Rule } from "@blindspot/core";
import { rootUserRule } from "./docker/root-user.js";
import { missingExampleVariableRule } from "./env/missing-example-variable.js";
import { trackedEnvRule } from "./git/tracked-env.js";
import { nodeVersionMismatchRule } from "./runtime/node-version-mismatch.js";
import { packageManagerMismatchRule } from "./runtime/package-manager-mismatch.js";
import { testsNotRunRule } from "./ci/tests-not-run.js";
import { nonDeterministicInstallRule } from "./ci/non-deterministic-install.js";
import { cachePackageManagerMismatchRule, scriptCommandMissingRule } from "./ci/repository-contracts.js";
import { envFileCopiedRule, npmInstallWithLockfileRule } from "./docker/repository-contracts.js";
import { missingNodeEnvRule } from "./docker/missing-node-env.js";
import { npmStartEntrypointRule } from "./docker/npm-start-entrypoint.js";
import { duplicateTemplateVariableRule } from "./env/duplicate-template-variable.js";
import { dependencyDirectoryCommittedRule, ignoredLockfileRule, trackedPrivateKeyRule } from "./git/repository-contracts.js";
import { monorepoEngineDriftRule, monorepoMultipleLockfilesRule, monorepoPackageManagerDriftRule } from "./monorepo/repository-contracts.js";
import { npmFilesExcludesRuntimeRule, npmFilesIncludesSecretRule, publishPrivatePackageRule } from "./release/repository-contracts.js";
import { missingLockfileRule, multipleLockfilesRule, packageManagerFieldDriftRule } from "./runtime/repository-contracts.js";

export { rootUserRule, missingExampleVariableRule, trackedEnvRule, nodeVersionMismatchRule, packageManagerMismatchRule, testsNotRunRule, nonDeterministicInstallRule, cachePackageManagerMismatchRule, scriptCommandMissingRule, envFileCopiedRule, npmInstallWithLockfileRule, missingNodeEnvRule, npmStartEntrypointRule, duplicateTemplateVariableRule, dependencyDirectoryCommittedRule, ignoredLockfileRule, trackedPrivateKeyRule, monorepoEngineDriftRule, monorepoMultipleLockfilesRule, monorepoPackageManagerDriftRule, npmFilesExcludesRuntimeRule, npmFilesIncludesSecretRule, publishPrivatePackageRule, missingLockfileRule, multipleLockfilesRule, packageManagerFieldDriftRule };
export const builtInRules: readonly Rule[] = [trackedEnvRule, dependencyDirectoryCommittedRule, ignoredLockfileRule, trackedPrivateKeyRule, rootUserRule, envFileCopiedRule, npmInstallWithLockfileRule, missingNodeEnvRule, npmStartEntrypointRule, missingExampleVariableRule, duplicateTemplateVariableRule, nodeVersionMismatchRule, packageManagerMismatchRule, missingLockfileRule, multipleLockfilesRule, packageManagerFieldDriftRule, testsNotRunRule, nonDeterministicInstallRule, cachePackageManagerMismatchRule, scriptCommandMissingRule, monorepoEngineDriftRule, monorepoMultipleLockfilesRule, monorepoPackageManagerDriftRule, npmFilesExcludesRuntimeRule, npmFilesIncludesSecretRule, publishPrivatePackageRule];
